/**
* Generated by go-doudou v2.1.8.
* Don't edit!
 */
package client

import (
	"context"

	"github.com/go-resty/resty/v2"
	"github.com/shinemost/helloworld/dto"
)

type Options struct {
	GzipReqBody bool
}

type IHelloworldClient interface {
	PostGenStudent(ctx context.Context, _headers map[string]string, body dto.Student, options Options) (_resp *resty.Response, data int32, err error)
	PostGenStudents(ctx context.Context, _headers map[string]string, body []dto.Student, options Options) (_resp *resty.Response, data []int32, err error)
	GetGenStudent_Id(ctx context.Context, _headers map[string]string, id int32, options Options) (_resp *resty.Response, data dto.Student, err error)
	PutGenStudent(ctx context.Context, _headers map[string]string, body dto.Student, options Options) (_resp *resty.Response, re error)
	DeleteGenStudent_Id(ctx context.Context, _headers map[string]string, id int32, options Options) (_resp *resty.Response, re error)
	GetGenStudents(ctx context.Context, _headers map[string]string, parameter dto.Parameter, options Options) (_resp *resty.Response, data dto.Page, err error)
}
