// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameStudent = "student"

// Student mapped from table <student>
type Student struct {
	ID   int32  `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id,omitempty"`
	Name string `gorm:"column:name;type:varchar(50);not null" json:"name,omitempty"`
	Sex  string `gorm:"column:sex;type:varchar(10);not null" json:"sex,omitempty"`
	Age  int32  `gorm:"column:age;type:int(11);not null" json:"age,omitempty"`
	Addr string `gorm:"column:addr;type:varchar(100);not null" json:"addr,omitempty"`
}

// TableName Student's table name
func (*Student) TableName() string {
	return TableNameStudent
}
