// Code generated by gorm.io/gen for go-doudou. YOU CAN EDIT.
// Code generated by gorm.io/gen for go-doudou. YOU CAN EDIT.
// Code generated by gorm.io/gen for go-doudou. YOU CAN EDIT.

package service

import (
	"context"

	"github.com/shinemost/helloworld/dto"
)

//go:generate go-doudou svc http -c
//go:generate go-doudou svc grpc

type Helloworld interface {

	// PostGenStudent mapped from table <student>
	// Code generated by gorm.io/gen for go-doudou. DO NOT EDIT.
	PostGenStudent(ctx context.Context, body dto.Student) (data int32, err error)

	// PostGenStudents mapped from table <student>
	// Code generated by gorm.io/gen for go-doudou. DO NOT EDIT.
	PostGenStudents(ctx context.Context, body []dto.Student) (data []int32, err error)

	// GetGenStudent_Id mapped from table <student>
	// Code generated by gorm.io/gen for go-doudou. DO NOT EDIT.
	GetGenStudent_Id(ctx context.Context, id int32) (data dto.Student, err error)

	// PutGenStudent mapped from table <student>
	// Code generated by gorm.io/gen for go-doudou. DO NOT EDIT.
	PutGenStudent(ctx context.Context, body dto.Student) error

	// DeleteGenStudent_Id mapped from table <student>
	// Code generated by gorm.io/gen for go-doudou. DO NOT EDIT.
	DeleteGenStudent_Id(ctx context.Context, id int32) error

	// GetGenStudents mapped from table <student>
	// Code generated by gorm.io/gen for go-doudou. DO NOT EDIT.
	GetGenStudents(ctx context.Context, parameter dto.Parameter) (data dto.Page, err error)
}
