//*
// Generated by go-doudou v2.1.8.
// Don't edit!
//
// Version No.: v20230919

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: transport/grpc/helloworld.proto

package grpc

import (
	any1 "github.com/golang/protobuf/ptypes/any"
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteGenStudentIdRpcRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteGenStudentIdRpcRequest) Reset() {
	*x = DeleteGenStudentIdRpcRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_helloworld_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGenStudentIdRpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGenStudentIdRpcRequest) ProtoMessage() {}

func (x *DeleteGenStudentIdRpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_helloworld_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGenStudentIdRpcRequest.ProtoReflect.Descriptor instead.
func (*DeleteGenStudentIdRpcRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_helloworld_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteGenStudentIdRpcRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GddUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Dept  string `protobuf:"bytes,4,opt,name=dept,proto3" json:"dept,omitempty"`
}

func (x *GddUser) Reset() {
	*x = GddUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_helloworld_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GddUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GddUser) ProtoMessage() {}

func (x *GddUser) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_helloworld_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GddUser.ProtoReflect.Descriptor instead.
func (*GddUser) Descriptor() ([]byte, []int) {
	return file_transport_grpc_helloworld_proto_rawDescGZIP(), []int{1}
}

func (x *GddUser) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GddUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GddUser) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *GddUser) GetDept() string {
	if x != nil {
		return x.Dept
	}
	return ""
}

type GetGenStudentIdRpcRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetGenStudentIdRpcRequest) Reset() {
	*x = GetGenStudentIdRpcRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_helloworld_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGenStudentIdRpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenStudentIdRpcRequest) ProtoMessage() {}

func (x *GetGenStudentIdRpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_helloworld_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGenStudentIdRpcRequest.ProtoReflect.Descriptor instead.
func (*GetGenStudentIdRpcRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_helloworld_proto_rawDescGZIP(), []int{2}
}

func (x *GetGenStudentIdRpcRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Page result wrapper
type Page struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items      []*any1.Any `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Page       int64       `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size       int64       `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	MaxPage    int64       `protobuf:"varint,4,opt,name=maxPage,proto3" json:"maxPage,omitempty"`
	TotalPages int64       `protobuf:"varint,5,opt,name=totalPages,proto3" json:"totalPages,omitempty"`
	Total      int64       `protobuf:"varint,6,opt,name=total,proto3" json:"total,omitempty"`
	Last       bool        `protobuf:"varint,7,opt,name=last,proto3" json:"last,omitempty"`
	First      bool        `protobuf:"varint,8,opt,name=first,proto3" json:"first,omitempty"`
	Visible    int64       `protobuf:"varint,9,opt,name=visible,proto3" json:"visible,omitempty"`
}

func (x *Page) Reset() {
	*x = Page{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_helloworld_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_helloworld_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_transport_grpc_helloworld_proto_rawDescGZIP(), []int{3}
}

func (x *Page) GetItems() []*any1.Any {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Page) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Page) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Page) GetMaxPage() int64 {
	if x != nil {
		return x.MaxPage
	}
	return 0
}

func (x *Page) GetTotalPages() int64 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *Page) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Page) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

func (x *Page) GetFirst() bool {
	if x != nil {
		return x.First
	}
	return false
}

func (x *Page) GetVisible() int64 {
	if x != nil {
		return x.Visible
	}
	return 0
}

// Parameter struct
type Parameter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page    int64       `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size    int64       `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Sort    string      `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	Order   string      `protobuf:"bytes,4,opt,name=order,proto3" json:"order,omitempty"`
	Fields  string      `protobuf:"bytes,5,opt,name=fields,proto3" json:"fields,omitempty"`
	Filters []*any1.Any `protobuf:"bytes,6,rep,name=filters,proto3" json:"filters,omitempty"`
}

func (x *Parameter) Reset() {
	*x = Parameter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_helloworld_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Parameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parameter) ProtoMessage() {}

func (x *Parameter) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_helloworld_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parameter.ProtoReflect.Descriptor instead.
func (*Parameter) Descriptor() ([]byte, []int) {
	return file_transport_grpc_helloworld_proto_rawDescGZIP(), []int{4}
}

func (x *Parameter) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Parameter) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Parameter) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *Parameter) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *Parameter) GetFields() string {
	if x != nil {
		return x.Fields
	}
	return ""
}

func (x *Parameter) GetFilters() []*any1.Any {
	if x != nil {
		return x.Filters
	}
	return nil
}

type PostGenStudentRpcResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data int32 `protobuf:"varint,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PostGenStudentRpcResponse) Reset() {
	*x = PostGenStudentRpcResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_helloworld_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostGenStudentRpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostGenStudentRpcResponse) ProtoMessage() {}

func (x *PostGenStudentRpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_helloworld_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostGenStudentRpcResponse.ProtoReflect.Descriptor instead.
func (*PostGenStudentRpcResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_helloworld_proto_rawDescGZIP(), []int{5}
}

func (x *PostGenStudentRpcResponse) GetData() int32 {
	if x != nil {
		return x.Data
	}
	return 0
}

type PostGenStudentsRpcRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body []*Student `protobuf:"bytes,1,rep,name=body,proto3" json:"body,omitempty"`
}

func (x *PostGenStudentsRpcRequest) Reset() {
	*x = PostGenStudentsRpcRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_helloworld_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostGenStudentsRpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostGenStudentsRpcRequest) ProtoMessage() {}

func (x *PostGenStudentsRpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_helloworld_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostGenStudentsRpcRequest.ProtoReflect.Descriptor instead.
func (*PostGenStudentsRpcRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_helloworld_proto_rawDescGZIP(), []int{6}
}

func (x *PostGenStudentsRpcRequest) GetBody() []*Student {
	if x != nil {
		return x.Body
	}
	return nil
}

type PostGenStudentsRpcResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []int32 `protobuf:"varint,1,rep,packed,name=data,proto3" json:"data,omitempty"`
}

func (x *PostGenStudentsRpcResponse) Reset() {
	*x = PostGenStudentsRpcResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_helloworld_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostGenStudentsRpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostGenStudentsRpcResponse) ProtoMessage() {}

func (x *PostGenStudentsRpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_helloworld_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostGenStudentsRpcResponse.ProtoReflect.Descriptor instead.
func (*PostGenStudentsRpcResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_helloworld_proto_rawDescGZIP(), []int{7}
}

func (x *PostGenStudentsRpcResponse) GetData() []int32 {
	if x != nil {
		return x.Data
	}
	return nil
}

// Student mapped from table <student>
type Student struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sex  string `protobuf:"bytes,3,opt,name=sex,proto3" json:"sex,omitempty"`
	Age  int32  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	Addr string `protobuf:"bytes,5,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (x *Student) Reset() {
	*x = Student{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_helloworld_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Student) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Student) ProtoMessage() {}

func (x *Student) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_helloworld_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Student.ProtoReflect.Descriptor instead.
func (*Student) Descriptor() ([]byte, []int) {
	return file_transport_grpc_helloworld_proto_rawDescGZIP(), []int{8}
}

func (x *Student) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Student) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Student) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *Student) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Student) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

var File_transport_grpc_helloworld_proto protoreflect.FileDescriptor

var file_transport_grpc_helloworld_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0a, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x1a, 0x19, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61,
	0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2e, 0x0a, 0x1c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47,
	0x65, 0x6e, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x70, 0x63, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x57, 0x0a, 0x07, 0x47, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65,
	0x70, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x70, 0x74, 0x22, 0x2b,
	0x0a, 0x19, 0x47, 0x65, 0x74, 0x47, 0x65, 0x6e, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x52, 0x70, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0xee, 0x01, 0x0a, 0x04,
	0x50, 0x61, 0x67, 0x65, 0x12, 0x2a, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x78, 0x50,
	0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6d, 0x61, 0x78, 0x50, 0x61,
	0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67,
	0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x61, 0x73, 0x74,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x6c, 0x61, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x66, 0x69, 0x72, 0x73, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x69, 0x72,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x22, 0xa5, 0x01, 0x0a,
	0x09, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x12, 0x2e, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x73, 0x22, 0x2f, 0x0a, 0x19, 0x50, 0x6f, 0x73, 0x74, 0x47, 0x65, 0x6e, 0x53,
	0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x70, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x44, 0x0a, 0x19, 0x50, 0x6f, 0x73, 0x74, 0x47, 0x65, 0x6e,
	0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x70, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x27, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x53, 0x74,
	0x75, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x30, 0x0a, 0x1a, 0x50,
	0x6f, 0x73, 0x74, 0x47, 0x65, 0x6e, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x70,
	0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x65, 0x0a,
	0x07, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x73, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x65, 0x78, 0x12, 0x10,
	0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x67, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x61, 0x64, 0x64, 0x72, 0x32, 0xf5, 0x03, 0x0a, 0x11, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f,
	0x72, 0x6c, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4f, 0x0a, 0x11, 0x50, 0x6f,
	0x73, 0x74, 0x47, 0x65, 0x6e, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x70, 0x63, 0x12,
	0x13, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x53, 0x74, 0x75,
	0x64, 0x65, 0x6e, 0x74, 0x1a, 0x25, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c,
	0x64, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x47, 0x65, 0x6e, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74,
	0x52, 0x70, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x63, 0x0a, 0x12, 0x50,
	0x6f, 0x73, 0x74, 0x47, 0x65, 0x6e, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x70,
	0x63, 0x12, 0x25, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x50,
	0x6f, 0x73, 0x74, 0x47, 0x65, 0x6e, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x70,
	0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f,
	0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x47, 0x65, 0x6e, 0x53, 0x74, 0x75,
	0x64, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x70, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x50, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x47, 0x65, 0x6e, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x52, 0x70, 0x63, 0x12, 0x25, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f,
	0x72, 0x6c, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x65, 0x6e, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x52, 0x70, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e,
	0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x53, 0x74, 0x75, 0x64, 0x65,
	0x6e, 0x74, 0x12, 0x3f, 0x0a, 0x10, 0x50, 0x75, 0x74, 0x47, 0x65, 0x6e, 0x53, 0x74, 0x75, 0x64,
	0x65, 0x6e, 0x74, 0x52, 0x70, 0x63, 0x12, 0x13, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f,
	0x72, 0x6c, 0x64, 0x2e, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x12, 0x59, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x65, 0x6e,
	0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x70, 0x63, 0x12, 0x28, 0x2e, 0x68,
	0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x47, 0x65, 0x6e, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x70, 0x63, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3c,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x47, 0x65, 0x6e, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x73,
	0x52, 0x70, 0x63, 0x12, 0x15, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64,
	0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x1a, 0x10, 0x2e, 0x68, 0x65, 0x6c,
	0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x42, 0x30, 0x5a, 0x2e,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x68, 0x69, 0x6e, 0x65,
	0x6d, 0x6f, 0x73, 0x74, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2f,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_transport_grpc_helloworld_proto_rawDescOnce sync.Once
	file_transport_grpc_helloworld_proto_rawDescData = file_transport_grpc_helloworld_proto_rawDesc
)

func file_transport_grpc_helloworld_proto_rawDescGZIP() []byte {
	file_transport_grpc_helloworld_proto_rawDescOnce.Do(func() {
		file_transport_grpc_helloworld_proto_rawDescData = protoimpl.X.CompressGZIP(file_transport_grpc_helloworld_proto_rawDescData)
	})
	return file_transport_grpc_helloworld_proto_rawDescData
}

var file_transport_grpc_helloworld_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_transport_grpc_helloworld_proto_goTypes = []interface{}{
	(*DeleteGenStudentIdRpcRequest)(nil), // 0: helloworld.DeleteGenStudentIdRpcRequest
	(*GddUser)(nil),                      // 1: helloworld.GddUser
	(*GetGenStudentIdRpcRequest)(nil),    // 2: helloworld.GetGenStudentIdRpcRequest
	(*Page)(nil),                         // 3: helloworld.Page
	(*Parameter)(nil),                    // 4: helloworld.Parameter
	(*PostGenStudentRpcResponse)(nil),    // 5: helloworld.PostGenStudentRpcResponse
	(*PostGenStudentsRpcRequest)(nil),    // 6: helloworld.PostGenStudentsRpcRequest
	(*PostGenStudentsRpcResponse)(nil),   // 7: helloworld.PostGenStudentsRpcResponse
	(*Student)(nil),                      // 8: helloworld.Student
	(*any1.Any)(nil),                     // 9: google.protobuf.Any
	(*empty.Empty)(nil),                  // 10: google.protobuf.Empty
}
var file_transport_grpc_helloworld_proto_depIdxs = []int32{
	9,  // 0: helloworld.Page.items:type_name -> google.protobuf.Any
	9,  // 1: helloworld.Parameter.filters:type_name -> google.protobuf.Any
	8,  // 2: helloworld.PostGenStudentsRpcRequest.body:type_name -> helloworld.Student
	8,  // 3: helloworld.HelloworldService.PostGenStudentRpc:input_type -> helloworld.Student
	6,  // 4: helloworld.HelloworldService.PostGenStudentsRpc:input_type -> helloworld.PostGenStudentsRpcRequest
	2,  // 5: helloworld.HelloworldService.GetGenStudentIdRpc:input_type -> helloworld.GetGenStudentIdRpcRequest
	8,  // 6: helloworld.HelloworldService.PutGenStudentRpc:input_type -> helloworld.Student
	0,  // 7: helloworld.HelloworldService.DeleteGenStudentIdRpc:input_type -> helloworld.DeleteGenStudentIdRpcRequest
	4,  // 8: helloworld.HelloworldService.GetGenStudentsRpc:input_type -> helloworld.Parameter
	5,  // 9: helloworld.HelloworldService.PostGenStudentRpc:output_type -> helloworld.PostGenStudentRpcResponse
	7,  // 10: helloworld.HelloworldService.PostGenStudentsRpc:output_type -> helloworld.PostGenStudentsRpcResponse
	8,  // 11: helloworld.HelloworldService.GetGenStudentIdRpc:output_type -> helloworld.Student
	10, // 12: helloworld.HelloworldService.PutGenStudentRpc:output_type -> google.protobuf.Empty
	10, // 13: helloworld.HelloworldService.DeleteGenStudentIdRpc:output_type -> google.protobuf.Empty
	3,  // 14: helloworld.HelloworldService.GetGenStudentsRpc:output_type -> helloworld.Page
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_transport_grpc_helloworld_proto_init() }
func file_transport_grpc_helloworld_proto_init() {
	if File_transport_grpc_helloworld_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_transport_grpc_helloworld_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteGenStudentIdRpcRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_helloworld_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GddUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_helloworld_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGenStudentIdRpcRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_helloworld_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Page); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_helloworld_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Parameter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_helloworld_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostGenStudentRpcResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_helloworld_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostGenStudentsRpcRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_helloworld_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostGenStudentsRpcResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_helloworld_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Student); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_transport_grpc_helloworld_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transport_grpc_helloworld_proto_goTypes,
		DependencyIndexes: file_transport_grpc_helloworld_proto_depIdxs,
		MessageInfos:      file_transport_grpc_helloworld_proto_msgTypes,
	}.Build()
	File_transport_grpc_helloworld_proto = out.File
	file_transport_grpc_helloworld_proto_rawDesc = nil
	file_transport_grpc_helloworld_proto_goTypes = nil
	file_transport_grpc_helloworld_proto_depIdxs = nil
}
