/**
* Generated by go-doudou v2.1.8.
* Don't edit!
 */
package httpsrv

import (
	"net/http"

	"github.com/unionj-cloud/go-doudou/v2/framework"
	"github.com/unionj-cloud/go-doudou/v2/framework/rest"
)

type HelloworldHandler interface {
	PostGenStudent(w http.ResponseWriter, r *http.Request)
	PostGenStudents(w http.ResponseWriter, r *http.Request)
	GetGenStudent_Id(w http.ResponseWriter, r *http.Request)
	PutGenStudent(w http.ResponseWriter, r *http.Request)
	DeleteGenStudent_Id(w http.ResponseWriter, r *http.Request)
	GetGenStudents(w http.ResponseWriter, r *http.Request)
}

func Routes(handler HelloworldHandler) []rest.Route {
	return []rest.Route{
		{
			Name:        "PostGenStudent",
			Method:      "POST",
			Pattern:     "/gen/student",
			HandlerFunc: handler.PostGenStudent,
		},
		{
			Name:        "PostGenStudents",
			Method:      "POST",
			Pattern:     "/gen/students",
			HandlerFunc: handler.PostGenStudents,
		},
		{
			Name:        "GetGenStudent_Id",
			Method:      "GET",
			Pattern:     "/gen/student/:id",
			HandlerFunc: handler.GetGenStudent_Id,
		},
		{
			Name:        "PutGenStudent",
			Method:      "PUT",
			Pattern:     "/gen/student",
			HandlerFunc: handler.PutGenStudent,
		},
		{
			Name:        "DeleteGenStudent_Id",
			Method:      "DELETE",
			Pattern:     "/gen/student/:id",
			HandlerFunc: handler.DeleteGenStudent_Id,
		},
		{
			Name:        "GetGenStudents",
			Method:      "GET",
			Pattern:     "/gen/students",
			HandlerFunc: handler.GetGenStudents,
		},
	}
}

var RouteAnnotationStore = framework.AnnotationStore{}
