// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"github.com/unionj-cloud/go-doudou/v2/toolkit/gormgen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q       = new(Query)
	Student *student
)

func SetDefault(db *gorm.DB, opts ...gormgen.DOOption) {
	*Q = *Use(db, opts...)
	Student = &Q.Student
}

func Use(db *gorm.DB, opts ...gormgen.DOOption) *Query {
	return &Query{
		db:      db,
		Student: newStudent(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Student student
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) Clone(db *gorm.DB) *Query {
	return &Query{
		db:      db,
		Student: q.Student.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:      db,
		Student: q.Student.replaceDB(db),
	}
}

type queryCtx struct {
	Student IStudentDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Student: q.Student.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.Clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.Clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
